### PR TITLE
#1272 update python version to 3.7

### PR DESCRIPTION
**Pull request by jkhlr**
- Updated python version in vagrant VM
- Updated python version for TravisCI
- Added some tests

### CODE REVIEW

**Comment by jkhlr** [comment]
Codacy can apparently not be upgraded to support new python features (e.g. dictionary unpacking) :(

**Comment by karyon** [comment]
codacy only uses some other linters, e.g. prospector, which throws that error. prospector in turn runs multiple other linters and merges their results. could you run prospector locally and find out where the syntax error comes from? then we could make a bug report/feature request to the respective project.

**Comment by jkhlr** [comment]
> codacy only uses some other linters, e.g. prospector, which throws that error. prospector in turn runs multiple other linters and merges their results. could you run prospector locally and find out where the syntax error comes from? then we could make a bug report/feature request to the respective project.

Codacy uses PyLint to lint python code. To define which python version it should lint for, you simply run pylint with the corresponding python version (https://stackoverflow.com/questions/23052637/specify-which-python-version-pylint-should-evaluate-for). Unfortunately, we don't have control over the python runtime Codacy uses, the only option we have is to choose between python2 and python3 (https://support.codacy.com/hc/en-us/articles/115002330985-Specifying-your-Python-version). So this is definitely a problem with Codacy. Probably they are running all linters on the same, not-so-recent python version :(

**Comment by karyon** [comment]
as far as i can see, it's prospector that complains about the syntax. if you expand the "invalid syntax" error in codacy, it says `Prospector_F999` at the bottom.

i just checked and we can enable prospector and pylint separately in codacy. no idea why their pylint does not complain but their prospector does...

**Comment by karyon** [comment]
I've reported the problem to codacy. In the meantime, we decided to go ahead and merge this. For the time being we'll ignore the syntax errors on codacy. In case they won't fix this or don't reply, we can think about building a workaround or disabling prospector.

**Comment by karyon** [comment]
thanks @jkhlr!

**Pull request merged**
